// vue/src/views/products/products.vue
<template>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <!-- breadcrumb-->
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li aria-current="page" class="breadcrumb-item active">Ladies</li>
          </ol>
        </nav>
      </div>

      <div class="col-lg-12">
        <div class="box info-bar">
          <div class="row">
            <div class="col-md-12 col-lg-4 products-showing">
              Showing <strong>{{ maxResultCount }}</strong> of
              <strong>{{ totalCount }}</strong> products
            </div>
            <div class="col-md-12 col-lg-7 products-number-sort">
              <div
                class="form-inline d-block d-lg-flex justify-content-between flex-column flex-md-row"
              >
                <div class="products-number">
                  <strong>Show</strong
                  ><button
                    v-on:click="maxResultCountChange(1)"
                    href="#"
                    class="btn btn-outline-secondary btn-sm"
                  >
                    1</button
                  ><button
                    v-on:click="maxResultCountChange(2)"
                    href="#"
                    class="btn btn-outline-secondary btn-sm"
                  >
                    2</button
                  ><button
                    v-on:click="maxResultCountChange(totalCount)"
                    href="#"
                    class="btn btn-outline-secondary btn-sm"
                  >
                    All</button
                  ><span>products</span>
                </div>
                <div class="products-sort-by mt-2 mt-lg-0">
                  <strong>Sort by Price</strong>
                  <button
                    v-on:click="SortByPrice"
                    v-if="!isSorted"
                    class="btn btn-primary"
                  >
                    Sort
                  </button>
                  <button
                    v-on:click="SortByPrice"
                    v-if="isSorted"
                    class="btn btn-danger"
                  >
                    Remove Filter
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row products">
          <div
            class="col-lg-4 col-md-6"
            v-for="product in list"
            :key="product.id"
          >
            <Product :product="product" />
          </div>
          <!-- /.products-->
        </div>
      </div>
      <!-- /.col-lg-9-->
    </div>
  </div>
</template>

<script lang="ts">
import AbpBase from "../../lib/abpbase";
import Product from "./product/product.vue";
import Util from "@/lib/util";
import Component from "vue-class-component";
import PageRequest from "@/store/entities/page-request";
class PageUserRequest extends PageRequest {
  keyword: string;
  isActive: boolean = null; //nullable
  from: Date;
  to: Date;
}
@Component({
  components: {
    Product,
  },
})
export default class Products extends AbpBase {
  //filters
  pagerequest: PageUserRequest = new PageUserRequest();
  creationTime: Date[] = [];
  async created() {
    this.getpage();
  }
  SortByPrice() {
    this.$store.commit("product/setSort");
    this.getpage();
  }
  get list() {
    return this.$store.state.product.list;
  }
  maxResultCountChange(maxResultCount: number) {
    this.$store.commit("product/setMaxResultCount", maxResultCount);
    this.getpage();
  }
  pageChange(page: number) {
    this.$store.commit("product/setCurrentPage", page);
    this.getpage();
  }
  pagesizeChange(pagesize: number) {
    this.$store.commit("product/setPageSize", pagesize);
    this.getpage();
  }
  async getpage() {
    this.pagerequest.maxResultCount = this.pageSize;
    this.pagerequest.skipCount = (this.currentPage - 1) * this.pageSize;
    //filters

    if (this.creationTime.length > 0) {
      this.pagerequest.from = this.creationTime[0];
    }
    if (this.creationTime.length > 1) {
      this.pagerequest.to = this.creationTime[1];
    }

    await this.$store.dispatch({
      type: "product/getAll",
      data: this.pagerequest,
    });
  }
  get maxResultCount() {
    return this.$store.state.product.maxResultCount;
  }
  get isSorted() {
    return this.$store.state.product.isSorted;
  }
  get pageSize() {
    return this.$store.state.product.pageSize;
  }
  get totalCount() {
    return this.$store.state.product.totalCount;
  }
  get currentPage() {
    return this.$store.state.product.currentPage;
  }
}
</script>

<style></style>

// reactjs/src/scenes/Products/index.tsx
import React from 'react';
import Product from './components/product';
import ProductStore from '../../stores/productStore';
import { FormComponentProps } from 'antd/lib/form';
import AppComponentBase from '../../components/AppComponentBase';
import { observer, inject } from 'mobx-react';
import Stores from '../../stores/storeIdentifier';
export interface IProductProps extends FormComponentProps {
  productStore: ProductStore;
}

export interface IProductState {
  modalVisible: boolean;
  maxResultCount: number;
  skipCount: number;
  productId: number;
  filter: string;
  isSorted:boolean;
}
@inject(Stores.ProductStore)
@observer
class Products extends AppComponentBase<IProductProps, IProductState> {
  state = {
    modalVisible: false,
    maxResultCount: 1,
    skipCount: 0,
    productId: 0,
    filter: '',
    isSorted:false,
  };
  async componentDidMount() {
    await this.getAll();
  }
  SortByPrice=()=>{
    this.setState({isSorted:!this.state.isSorted},async ()=>await this.getAll());
  }
  handleShowChange = (e: any) => {
    this.setState({ maxResultCount: e }, async () => await this.getAll());
  };
  async getAll() {
    await this.props.productStore.getAll({ maxResultCount: this.state.maxResultCount, skipCount: this.state.skipCount, keyword: this.state.filter },this.state.isSorted);
  }
  public render() {
    return (
      <div className="container">
        <div className="row">
          <div className="col-lg-12">
            <div className="box info-bar">
              <div className="row">
                <div className="col-md-12 col-lg-4 products-showing">
    Showing <strong>{this.state.maxResultCount}</strong> of <strong>{this.props.productStore.products?.totalCount}</strong> products
                </div>
                <div className="col-md-12 col-lg-7 products-number-sort">
                  <div className="form-inline d-block d-lg-flex justify-content-between flex-column flex-md-row">
                  <div className="products-number">
                    <strong>Show</strong>
                    <button onClick={() => this.handleShowChange(1)} className="btn btn-outline-secondary btn-sm">
                      1
                    </button>
                    <button onClick={() => this.handleShowChange(2)} className="btn btn-outline-secondary btn-sm">
                      2
                    </button>
                    <button onClick={() => this.handleShowChange(this.props.productStore.products.totalCount)} className="btn btn-outline-secondary btn-sm">
                      All
                    </button>
                    <span>products</span>
                  </div>
                  <div className="products-sort-by mt-2 mt-lg-0">  
                  <span>Sort By Price </span>   
                  {
                    !this.state.isSorted?(
                    <button onClick={this.SortByPrice} className="btn btn-primary">
                      Sort
                    </button>
                    ):(
                      <button onClick={this.SortByPrice} className="btn btn-danger">
                      Remove Filter
                    </button>
                    )
                  }               
                  </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="row products">
              {this.props.productStore.products?.items.map((item) => (
                <div key={item.id} className="col-lg-4 col-md-6">
                  <Product name={item.name} price={item.price} imgUrl={item.imgUrl} />
                </div>
              ))}

              {/* <div className="pages">
                <p className="loadMore">
                  <a href="#" className="btn btn-primary btn-lg">
                    <i className="fa fa-chevron-down"></i> Load more
                  </a>
                </p>
                <nav aria-label="Page navigation example" className="d-flex justify-content-center">
                  <ul className="pagination">
                    <li className="page-item">
                      <a href="#" aria-label="Previous" className="page-link">
                        <span aria-hidden="true">«</span>
                        <span className="sr-only">Previous</span>
                      </a>
                    </li>
                    <li className="page-item active">
                      <a href="#" className="page-link">
                        1
                      </a>
                    </li>
                    <li className="page-item">
                      <a href="#" className="page-link">
                        2
                      </a>
                    </li>
                    <li className="page-item">
                      <a href="#" className="page-link">
                        3
                      </a>
                    </li>
                    <li className="page-item">
                      <a href="#" className="page-link">
                        4
                      </a>
                    </li>
                    <li className="page-item">
                      <a href="#" className="page-link">
                        5
                      </a>
                    </li>
                    <li className="page-item">
                      <a href="#" aria-label="Next" className="page-link">
                        <span aria-hidden="true">»</span>
                        <span className="sr-only">Next</span>
                      </a>
                    </li>
                  </ul>
                </nav>
              </div>
            </div> */}
            </div>
          </div>
        </div>
      </div>
    );
  }
}
export default Products;
